// <auto-generated />
namespace WEBCRAFT.MobileStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PartnerId_Added_To_Account1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PartnerId_Added_To_Account1));
        
        string IMigrationMetadata.Id
        {
            get { return "201708011153409_PartnerId_Added_To_Account1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
