// <auto-generated />
namespace WEBCRAFT.MobileStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Createmtominventoryproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createmtominventoryproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201812301630583_Create-m-to-m-inventory-product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
