// <auto-generated />
namespace WEBCRAFT.MobileStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createInventorywithmtomProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createInventorywithmtomProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201812301543138_create-Inventory-with-m-to-m-Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
