// <auto-generated />
namespace WEBCRAFT.MobileStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_brand_to_Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_brand_to_Category));
        
        string IMigrationMetadata.Id
        {
            get { return "201810011837400_Change_brand_to_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
