// <auto-generated />
namespace WEBCRAFT.MobileStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixing_StockItem_Keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixing_StockItem_Keys));
        
        string IMigrationMetadata.Id
        {
            get { return "201901092127344_fixing_StockItem_Keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
