//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advensco.EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    //repo class 
    public class  C__MigrationHistoryRepository : Repository<C__MigrationHistory >
    {
    
        public C__MigrationHistoryRepository(Entities context)
            : base(context)
        {
        }
    }//1
    //repo class 
    public partial class C__MigrationHistory
    {
        public string MigrationId { get; set; }
        public string ContextKey { get; set; }
        public byte[] Model { get; set; }
        public string ProductVersion { get; set; }
    }


}
