//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advensco.EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    //repo class 
    public class  ItemsOperationRepository : Repository<ItemsOperation >
    {
    
        public ItemsOperationRepository(Entities context)
            : base(context)
        {
        }
    }//1
    //repo class 
    public partial class ItemsOperation
    {
        public System.Guid Id { get; set; }
        public string OperationType { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedBy { get; set; }
        public string ExecutedBy { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<System.Guid> WarehouseId { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }


}
