//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advensco.EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    //repo class 
    public class  WarehouseItemRepository : Repository<WarehouseItem >
    {
    
        public WarehouseItemRepository(Entities context)
            : base(context)
        {
        }
    }//1
    //repo class 
    public partial class WarehouseItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public Nullable<System.Guid> WarehouseId { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> CheckedOut { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }


// my code here 
}//1
